# use Ganache's forked mainnet mode as the default network

networks:
  default: mainnet-fork

autofetch_sources: true

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.1.0
  - Uniswap/v3-periphery@1.3.0
  - Uniswap/v3-core@1.0.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"
      - "@uniswap/v3-periphery=Uniswap/v3-periphery@1.3.0"
      - "@uniswap/v3-core=Uniswap/v3-core@1.0.0"

reports:
  exclude_paths:
    - contracts/test/Token.sol
    - contracts/test/TestGuestList.sol
  exclude_contracts:
    - SafeMath
    - SafeERC20
    - Address
